spring:
  application:
    name: projeto-game-store

  datasource:
    url: jdbc:postgresql://localhost:5432/gamestore
    username: postgres
    password: 86065542

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
